### ISSUE TITLE
8.제어문/9.타입변환과 단축평가

### ISSUE THREAD

**Issue by jungmyungjin** [JS-Deep-Divers/ModernJavaScriptDeepDive#2]
- [x] jungmyungjin
- [x] nkavay
- [x] LHI0915
- [x] buyeolim
- [x] seongm2n
- [x] ultraWiseWater

**Comment by seongm2n** [comment]
#2
### 새로운 사실!
[암묵적 타입 변환 또는 타입 강제 변환]
`var str = x + '';
console.log(typeof str, str //string 10`

[단축 평가]
[옵셔널 체이닝 연산자]

**Comment by nkavay** [comment]
#40
